Some shell fixes

diff --git a/shellrc_ext b/shellrc_ext
--- a/shellrc_ext
+++ b/shellrc_ext
@@ -20,7 +20,7 @@ export PATH="$HOME/.myprefix/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/go/bin:
 
 ## Use vim line editing mode
 set -o vi
-if ! [ "$ZSH_VERSION" = "" ]
+if [ -n "$ZSH_VERSION" ]
 then
     bindkey "^A" beginning-of-line
     bindkey "^E" end-of-line
@@ -103,31 +103,33 @@ doh()
     curl -H "Accept: application/dns-json" "https://dns.nextdns.io/dohtest?name=$1&type=${2:-A}" | jq '.Answer'
 }
 
-## Commit Homebrew cask zap updates: does not work with zsh
-commit_zap()
-(
-    cd "$(brew --repository homebrew/cask)/Casks" || return 1
-    cask_paths="$(git status -su | sed 's:^ M ::' | xargs)"
-
-    for caskpath in $cask_paths
-    do
-        cask="$(basename "$caskpath" .rb)"
-        echo "$cask" at "$caskpath"
-        brew audit --cask --online "$cask" || echo "brew audit failed for $cask"
-        brew style --fix "$cask" || echo "brew style failed for $cask"
-        brew cleanup --prune all
-        echo "Press enter to create the commit, or 's' to skip... "
-        read -r
-        if ! [ "v$REPLY" = "vs" ]
-        then
-            title="$cask: update zap stanza"
-            branch="zap-$cask"
-            git switch -c "$branch" || return 1
-            git add "$caskpath" || return 1
-            git commit -sm "$title" || return 1
-            git push myzhang1029 "$branch" || return 1
-
-            gh pr create --title "$title" --body-file - --base "homebrew:master" --head "myzhang1029:$branch" --web << 'EOF'
+if [ -n "$BASH_VERSION" ]
+then
+    ## Commit Homebrew cask zap updates: does not work with zsh
+    commit_zap()
+    (
+        cd "$(brew --repository homebrew/cask)/Casks" || return 1
+        cask_paths="$(git status -su | sed 's:^ M ::' | xargs)"
+    
+        for caskpath in $cask_paths
+        do
+            cask="$(basename "$caskpath" .rb)"
+            echo "$cask" at "$caskpath"
+            brew audit --cask --online "$cask" || echo "brew audit failed for $cask"
+            brew style --fix "$cask" || echo "brew style failed for $cask"
+            brew cleanup --prune all
+            echo "Press enter to create the commit, or 's' to skip... "
+            read -r
+            if ! [ "v$REPLY" = "vs" ]
+            then
+                title="$cask: update zap stanza"
+                branch="zap-$cask"
+                git switch -c "$branch" || return 1
+                git add "$caskpath" || return 1
+                git commit -sm "$title" || return 1
+                git push myzhang1029 "$branch" || return 1
+    
+                gh pr create --title "$title" --body-file - --base "homebrew:master" --head "myzhang1029:$branch" --web << 'EOF'
 After making any changes to a cask, existing or new, verify:
 
 - [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) \
@@ -135,11 +137,18 @@ or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-
 - [x] `brew audit --cask --online <cask>` is error-free.
 - [x] `brew style --fix <cask>` reports no offenses.'
 EOF
-            # Go to the previous commit
-            git switch -
-        fi
-    done
-)
+                # Go to the previous commit
+                git switch -
+            fi
+        done
+    )
+else
+    commit_zap()
+    {
+        echo "Use bash" >&2
+        exit 1
+    }
+fi
 
 # Aliases
 ## General aliases
@@ -211,7 +220,7 @@ alias fflistdev="ffmpeg -hide_banner -f avfoundation -list_devices true -i ''"
 [ -f ~/.local_aliases ] && . ~/.local_aliases
 
 
-if ! [ "$ZSH_VERSION" = "" ]
+if [ -n "$ZSH_VERSION" ]
 then
     # Session history
     alias lochist="fc -lLI 1"
@@ -254,7 +263,7 @@ then
     # arduino-cli completion
     if type arduino-cli > /dev/null 2>&1
     then
-        eval $(arduino-cli completion zsh)
+        eval "$(arduino-cli completion zsh)"
     fi
 else
     # Not zsh
@@ -304,7 +313,7 @@ else
     # arduino-cli completion
     if type arduino-cli > /dev/null 2>&1
     then
-        eval $(arduino-cli completion bash)
+        eval "$(arduino-cli completion bash)"
     fi
 fi
 
